version: '3.8'

services:
  book-reading-website:
    container_name: book-reading-website
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3005"
    environment:
      - NODE_ENV=production
    command: pnpm start
