name: Deploy Next.js App via SSH Pull & Build

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            APP_DIR="${{ secrets.APP_DIR }}"

            echo ">>> Go to app directory..."
            cd "$APP_DIR"

            echo ">>> Pull latest code..."
            git pull origin main

            echo ">>> Install dependencies..."
            npm ci

            echo ">>> Remove old Docker containers and images..."
            docker rm -f app || true
            docker rmi app || true

            echo ">>> Build app..."
            docker build --no-cache -t app .

            echo ">>> Run app..."
            docker run -d --name app -p 3000:3000 app

            echo ">>> Verify deployment..."
            docker ps | grep app
